### ISSUE TITLE
Overlapping των περιοχών γύρω από τα κουμπιά

### ISSUE THREAD

**Issue by nkotsonis** [IXG-Java-Team-03/JAVA-project#8]

**Comment by YiorgosX** [comment]
Μάλλον ψόφησε το project, ε;
Πάντως εγώ το προχώρησα το port μου στο unity, όσοι έχετε android ρίξτε του
μια ματιά εδώ:
https://play.google.com/store/apps/details?id=com.digicoo.lexiplastis
:)
